---@meta

trigger.EVENT_NONE= nil
trigger.EVENT_DISPLAY= nil
trigger.EVENT_NOTIFY1= nil
trigger.EVENT_NOTIFY2= nil
trigger.EVENT_NOTIFY3= nil
trigger.EVENT_COMMAND= nil
trigger.EVENT_DIGIO1= nil
trigger.EVENT_DIGIO2= nil
trigger.EVENT_DIGIO3= nil
trigger.EVENT_DIGIO4= nil
trigger.EVENT_DIGIO5= nil
trigger.EVENT_DIGIO6= nil
trigger.EVENT_TSPLINK1= nil
trigger.EVENT_TSPLINK2= nil
trigger.EVENT_TSPLINK3= nil
trigger.EVENT_LAN1= nil
trigger.EVENT_LAN2= nil
trigger.EVENT_LAN3= nil
trigger.EVENT_LAN4= nil
trigger.EVENT_LAN5= nil
trigger.EVENT_LAN6= nil
trigger.EVENT_LAN7= nil
trigger.EVENT_LAN8= nil
trigger.EVENT_ANALOGTRIGGER= nil
trigger.EVENT_BLENDER1= nil
trigger.EVENT_BLENDER2= nil
trigger.EVENT_BLENDER3= nil
trigger.EVENT_TIMER1= nil
trigger.EVENT_TIMER2= nil
trigger.EVENT_TIMER3= nil
trigger.EVENT_TIMER4= nil
trigger.EVENT_EXTERNAL= nil
trigger.EVENT_SCAN_ALARM_LIMIT= nil
trigger.EVENT_SCAN_CHANNEL_READY= nil
trigger.EVENT_SCAN_COMPLETE= nil
trigger.EVENT_SCAN_MEASURE_COMPLETE= nil
trigger.EVENT_SCAN_ALARM_LIMIT= nil

---@alias triggerEvents
---| `trigger.EVENT_NONE`
---| `trigger.EVENT_DISPLAY`
---| `trigger.EVENT_NOTIFY1`
---| `trigger.EVENT_NOTIFY2`
---| `trigger.EVENT_NOTIFY3`
---| `trigger.EVENT_COMMAND`
---| `trigger.EVENT_DIGIO1`
---| `trigger.EVENT_DIGIO2`
---| `trigger.EVENT_DIGIO3`
---| `trigger.EVENT_DIGIO4`
---| `trigger.EVENT_DIGIO5`
---| `trigger.EVENT_DIGIO6`
---| `trigger.EVENT_TSPLINK1`
---| `trigger.EVENT_TSPLINK2`
---| `trigger.EVENT_TSPLINK3`
---| `trigger.EVENT_LAN1`
---| `trigger.EVENT_LAN2`
---| `trigger.EVENT_LAN3`
---| `trigger.EVENT_LAN4`
---| `trigger.EVENT_LAN5`
---| `trigger.EVENT_LAN6`
---| `trigger.EVENT_LAN7`
---| `trigger.EVENT_LAN8`
---| `trigger.EVENT_ANALOGTRIGGER`
---| `trigger.EVENT_BLENDER1`
---| `trigger.EVENT_BLENDER2`
---| `trigger.EVENT_BLENDER3`
---| `trigger.EVENT_TIMER1`
---| `trigger.EVENT_TIMER2`
---| `trigger.EVENT_TIMER3`
---| `trigger.EVENT_TIMER4`
---| `trigger.EVENT_EXTERNAL`
---| `trigger.EVENT_SCAN_ALARM_LIMIT`
---| `trigger.EVENT_SCAN_CHANNEL_READY`
---| `trigger.EVENT_SCAN_COMPLETE`
---| `trigger.EVENT_SCAN_MEASURE_COMPLETE`
---| `trigger.EVENT_SCAN_ALARM_LIMIT`

