---@meta

---@alias setblockalias
---| `trigger.BLOCK_BRANCH_ALWAYS`
---| `trigger.BLOCK_BRANCH_COUNTER`
---| `trigger.BLOCK_BRANCH_DELTA`
---| `trigger.BLOCK_BRANCH_LIMIT_CONSTANT`
---| `trigger.BLOCK_BRANCH_LIMIT_DYNAMIC`
---| `trigger.BLOCK_BRANCH_ON_EVENT`
---| `trigger.BLOCK_BRANCH_ONCE`
---| `trigger.BLOCK_BRANCH_ONCE_EXCLUDED`
---| `trigger.BLOCK_BUFFER_CLEAR`
---| `trigger.BLOCK_CONFIG_NEXT`
---| `trigger.BLOCK_CONFIG_PREV`
---| `trigger.BLOCK_CONFIG_RECALL`
---| `trigger.BLOCK_DELAY_CONSTANT`
---| `trigger.BLOCK_DELAY_DYNAMIC`
---| `trigger.BLOCK_DIGITAL_IO`
---| `trigger.BLOCK_LOG_EVENT`
---| `trigger.BLOCK_MEASURE`
---| `trigger.BLOCK_MEASURE_DIGITIZE`
---| `trigger.BLOCK_NOP`
---| `trigger.BLOCK_NOTIFY`
---| `trigger.BLOCK_RESET_BRANCH_COUNT`
---| `trigger.BLOCK_SOURCE_OUTPUT`
---| `trigger.BLOCK_WAIT`