---@meta

smu.ATTR_SRC_RANGE_AUTO = nil
smu.ATTR_SRC_DELAY_AUTO = nil
smu.ATTR_SRC_DELAY = nil
smu.ATTR_SRC_FUNCTION = nil
smu.ATTR_SRC_HIGHC = nil
smu.ATTR_SRC_LEVEL = nil
smu.ATTR_SRC_LIMIT_LEVEL = nil
smu.ATTR_SRC_OFFMODE = nil
smu.ATTR_SRC_PROTECT_LEVEL = nil
smu.ATTR_SRC_PROTECT_TRIPPED = nil
smu.ATTR_SRC_RANGE = nil
smu.ATTR_SRC_READBACK = nil
smu.ATTR_SRC_LIMIT_TRIPPED = nil
smu.ATTR_SRC_USER_DELAY_1 = nil
smu.ATTR_SRC_USER_DELAY_2 = nil
smu.ATTR_SRC_USER_DELAY_3 = nil
smu.ATTR_SRC_USER_DELAY_4 = nil
smu.ATTR_SRC_USER_DELAY_5 = nil

---@alias smuSourceGetSetAttributes
---|`smu.ATTR_SRC_RANGE_AUTO`
---|`smu.ATTR_SRC_DELAY_AUTO`
---|`smu.ATTR_SRC_DELAY`
---|`smu.ATTR_SRC_FUNCTION`
---|`smu.ATTR_SRC_HIGHC`
---|`smu.ATTR_SRC_LEVEL`
---|`smu.ATTR_SRC_LIMIT_LEVEL`
---|`smu.ATTR_SRC_OFFMODE`
---|`smu.ATTR_SRC_PROTECT_LEVEL`
---|`smu.ATTR_SRC_PROTECT_TRIPPED`
---|`smu.ATTR_SRC_RANGE`
---|`smu.ATTR_SRC_READBACK`
---|`smu.ATTR_SRC_LIMIT_TRIPPED`
---|`smu.ATTR_SRC_USER_DELAY_1`
---|`smu.ATTR_SRC_USER_DELAY_2`
---|`smu.ATTR_SRC_USER_DELAY_3`
---|`smu.ATTR_SRC_USER_DELAY_4`
---|`smu.ATTR_SRC_USER_DELAY_5`