---@meta

dmm.ATTR_MEAS_TWO_RTD= nil
dmm.ATTR_DIGI_MATH_ENABLE= nil
dmm.ATTR_MEAS_REL_METHOD= nil
dmm.DIGITS_4_5= nil
dmm.ATTR_MEAS_NPLC= nil
dmm.ATTR_MEAS_OPEN_DETECTOR= nil
dmm.ATTR_MEAS_MATH_MXB_BF= nil
dmm.ATTR_MEAS_LIMIT_AUDIBLE_2= nil
dmm.ATTR_MEAS_ATRIG_EDGE_LEVEL= nil
dmm.ATTR_MEAS_THERMOCOUPLE= nil
dmm.ATTR_MEAS_LINE_SYNC= nil
dmm.ATTR_MEAS_RTD_ZERO= nil
dmm.ATTR_DIGI_LIMIT_AUDIBLE_2= nil
dmm.ATTR_DIGI_RANGE= nil
dmm.ATTR_DIGI_ATRIG_EDGE_SLOPE= nil
dmm.ATTR_MEAS_THRESHOLD_RANGE_AUTO= nil
dmm.ATTR_DIGI_SAMPLE_RATE= nil
dmm.ATTR_DIGI_USER_DELAY_N= nil
dmm.ATTR_MEAS_FILTER_ENABLE= nil
dmm.ATTR_MEAS_SENSE_RANGE= nil
dmm.ATTR_MEAS_DETECTBW= nil
dmm.ATTR_DIGI_LIMIT_ENABLE_1= nil
dmm.ATTR_MEAS_LIMIT_HIGH_2= nil
dmm.ATTR_MEAS_ATRIG_WINDOW_LEVEL_LOW= nil
dmm.ATTR_MEAS_DIGITS= nil
dmm.ATTR_MEAS_TERMINALS= nil
dmm.ATTR_MEAS_LIMIT_AUTO_CLEAR_2= nil
dmm.ATTR_DIGI_LIMIT_LOW_2= nil
dmm.ATTR_MEAS_AUTO_ZERO= nil
dmm.ATTR_MEAS_THERMISTOR= nil
dmm.ATTR_DIGI_TERMINALS= nil
dmm.ATTR_MEAS_MATH_MXB_MF= nil
dmm.ATTR_MEAS_FOUR_RTD= nil
dmm.ATTR_MEAS_MATH_PERCENT= nil
dmm.ATTR_MEAS_DB_REFERENCE= nil
dmm.ATTR_DIGI_REL_ENABLE= nil
dmm.ATTR_DIGI_DIGITS= nil
dmm.ATTR_DIGI_APERTURE= nil
dmm.ATTR_MEAS_LIMIT_HIGH_1= nil
dmm.ATTR_MEAS_LIMIT_FAIL_2= nil
dmm.ATTR_DIGI_LIMIT_AUTO_CLEAR_1= nil
dmm.ATTR_MEAS_USER_DELAY_N= nil
dmm.ATTR_MEAS_RTD_ALPHA= nil
dmm.ATTR_DIGI_MATH_MXB_MF= nil
dmm.ATTR_DIGI_MATH_MXB_BF= nil
dmm.ATTR_MEAS_DBM_REFERENCE= nil
dmm.ATTR_MEAS_LIMIT_FAIL_1= nil
dmm.ATTR_MEAS_ATRIG_WINDOW_LEVEL_HIGH= nil
dmm.ATTR_MEAS_AUTO_DELAY= nil
dmm.ATTR_DIGI_ATRIG_WINDOW_LEVEL_HIGH= nil
dmm.ATTR_DIGI_MATH_FORMAT= nil
dmm.ATTR_DIGI_COUNT= nil
dmm.ATTR_MEAS_MATH_ENABLE= nil
dmm.ATTR_DIGI_LIMIT_HIGH_1= nil
dmm.ATTR_MEAS_RANGE= nil
dmm.ATTR_MEAS_LIMIT_ENABLE_2= nil
dmm.ATTR_MEAS_LIMIT_AUTO_CLEAR_1= nil
dmm.ATTR_MEAS_THREE_RTD= nil
dmm.ATTR_MEAS_ATRIG_WINDOW_DIRECTION= nil
dmm.ATTR_DIGI_LIMIT_FAIL_1= nil
dmm.ATTR_DIGI_UNIT= nil
dmm.ATTR_DIGI_LIMIT_FAIL_2= nil
dmm.ATTR_DIGI_INPUT_IMPEDANCE= nil
dmm.ATTR_DIGI_DBM_REFERENCE= nil
dmm.ATTR_MEAS_FILTER_TYPE= nil
dmm.ATTR_MEAS_REF_JUNCTION= nil
dmm.ATTR_MEAS_FILTER_COUNT= nil
dmm.ATTR_MEAS_ATRIG_EDGE_SLOPE= nil
dmm.ATTR_MEAS_TRANSDUCER= nil
dmm.ATTR_DIGI_ATRIG_MODE= nil
dmm.ATTR_MEAS_SIM_REF_TEMP= nil
dmm.ATTR_MEAS_APERTURE= nil
dmm.ATTR_MEAS_RTD_BETA= nil
dmm.ATTR_MEAS_BIAS_LEVEL= nil
dmm.ATTR_MEAS_COUNT= nil
dmm.ATTR_DIGI_ATRIG_EDGE_LEVEL= nil
dmm.ATTR_MEAS_THRESHOLD_RANGE= nil
dmm.ATTR_MEAS_FUNCTION= nil
dmm.ATTR_DIGI_ATRIG_WINDOW_LEVEL_LOW= nil
dmm.ATTR_MEAS_FILTER_WINDOW= nil
dmm.ATTR_DIGI_MATH_PERCENT= nil
dmm.ATTR_MEAS_LIMIT_LOW_2= nil
dmm.ATTR_DIGI_LIMIT_HIGH_2= nil
dmm.ATTR_DIGI_ATRIG_WINDOW_DIRECTION= nil
dmm.ATTR_MEAS_INPUT_IMPEDANCE= nil
dmm.ATTR_DIGI_LIMIT_AUDIBLE_1= nil
dmm.ATTR_DIGI_LIMIT_ENABLE_2= nil
dmm.ATTR_MEAS_MATH_FORMAT= nil
dmm.ATTR_DIGI_DB_REFERENCE= nil
dmm.ATTR_MEAS_LIMIT_ENABLE_1= nil
dmm.ATTR_MEAS_RANGE_AUTO= nil
dmm.ATTR_MEAS_LIMIT_AUDIBLE_1= nil
dmm.ATTR_MEAS_REL_ENABLE= nil
dmm.ATTR_MEAS_LIMIT_LOW_1= nil
dmm.ATTR_MEAS_REL_LEVEL= nil
dmm.ATTR_DIGI_REL_LEVEL= nil
dmm.ATTR_MEAS_UNIT= nil
dmm.ATTR_DIGI_FUNCTION= nil
dmm.ATTR_MEAS_OFFCOMP_ENABLE= nil
dmm.ATTR_DIGI_LIMIT_LOW_1= nil
dmm.ATTR_MEAS_RTD_DELTA= nil
dmm.ATTR_DIGI_LIMIT_AUTO_CLEAR_2= nil

---@alias functionAttributes
---|`dmm.ATTR_MEAS_TWO_RTD`
---|`dmm.ATTR_DIGI_MATH_ENABLE`
---|`dmm.ATTR_MEAS_REL_METHOD`
---|`dmm.DIGITS_4_5`
---|`dmm.ATTR_MEAS_NPLC`
---|`dmm.ATTR_MEAS_OPEN_DETECTOR`
---|`dmm.ATTR_MEAS_MATH_MXB_BF`
---|`dmm.ATTR_MEAS_LIMIT_AUDIBLE_2`
---|`dmm.ATTR_MEAS_ATRIG_EDGE_LEVEL`
---|`dmm.ATTR_MEAS_THERMOCOUPLE`
---|`dmm.ATTR_MEAS_LINE_SYNC`
---|`dmm.ATTR_MEAS_RTD_ZERO`
---|`dmm.ATTR_DIGI_LIMIT_AUDIBLE_2`
---|`dmm.ATTR_DIGI_RANGE`
---|`dmm.ATTR_DIGI_ATRIG_EDGE_SLOPE`
---|`dmm.ATTR_MEAS_THRESHOLD_RANGE_AUTO`
---|`dmm.ATTR_DIGI_SAMPLE_RATE`
---|`dmm.ATTR_DIGI_USER_DELAY_N`
---|`dmm.ATTR_MEAS_FILTER_ENABLE`
---|`dmm.ATTR_MEAS_SENSE_RANGE`
---|`dmm.ATTR_MEAS_DETECTBW`
---|`dmm.ATTR_DIGI_LIMIT_ENABLE_1`
---|`dmm.ATTR_MEAS_LIMIT_HIGH_2`
---|`dmm.ATTR_MEAS_ATRIG_WINDOW_LEVEL_LOW`
---|`dmm.ATTR_MEAS_DIGITS`
---|`dmm.ATTR_MEAS_TERMINALS`
---|`dmm.ATTR_MEAS_LIMIT_AUTO_CLEAR_2`
---|`dmm.ATTR_DIGI_LIMIT_LOW_2`
---|`dmm.ATTR_MEAS_AUTO_ZERO`
---|`dmm.ATTR_MEAS_THERMISTOR`
---|`dmm.ATTR_DIGI_TERMINALS`
---|`dmm.ATTR_MEAS_MATH_MXB_MF`
---|`dmm.ATTR_MEAS_FOUR_RTD`
---|`dmm.ATTR_MEAS_MATH_PERCENT`
---|`dmm.ATTR_MEAS_DB_REFERENCE`
---|`dmm.ATTR_DIGI_REL_ENABLE`
---|`dmm.ATTR_DIGI_DIGITS`
---|`dmm.ATTR_DIGI_APERTURE`
---|`dmm.ATTR_MEAS_LIMIT_HIGH_1`
---|`dmm.ATTR_MEAS_LIMIT_FAIL_2`
---|`dmm.ATTR_DIGI_LIMIT_AUTO_CLEAR_1`
---|`dmm.ATTR_MEAS_USER_DELAY_N`
---|`dmm.ATTR_MEAS_RTD_ALPHA`
---|`dmm.ATTR_DIGI_MATH_MXB_MF`
---|`dmm.ATTR_DIGI_MATH_MXB_BF`
---|`dmm.ATTR_MEAS_DBM_REFERENCE`
---|`dmm.ATTR_MEAS_LIMIT_FAIL_1`
---|`dmm.ATTR_MEAS_ATRIG_WINDOW_LEVEL_HIGH`
---|`dmm.ATTR_MEAS_AUTO_DELAY`
---|`dmm.ATTR_DIGI_ATRIG_WINDOW_LEVEL_HIGH`
---|`dmm.ATTR_DIGI_MATH_FORMAT`
---|`dmm.ATTR_DIGI_COUNT`
---|`dmm.ATTR_MEAS_MATH_ENABLE`
---|`dmm.ATTR_DIGI_LIMIT_HIGH_1`
---|`dmm.ATTR_MEAS_RANGE`
---|`dmm.ATTR_MEAS_LIMIT_ENABLE_2`
---|`dmm.ATTR_MEAS_LIMIT_AUTO_CLEAR_1`
---|`dmm.ATTR_MEAS_THREE_RTD`
---|`dmm.ATTR_MEAS_ATRIG_WINDOW_DIRECTION`
---|`dmm.ATTR_DIGI_LIMIT_FAIL_1`
---|`dmm.ATTR_DIGI_UNIT`
---|`dmm.ATTR_DIGI_LIMIT_FAIL_2`
---|`dmm.ATTR_DIGI_INPUT_IMPEDANCE`
---|`dmm.ATTR_DIGI_DBM_REFERENCE`
---|`dmm.ATTR_MEAS_FILTER_TYPE`
---|`dmm.ATTR_MEAS_REF_JUNCTION`
---|`dmm.ATTR_MEAS_FILTER_COUNT`
---|`dmm.ATTR_MEAS_ATRIG_EDGE_SLOPE`
---|`dmm.ATTR_MEAS_TRANSDUCER`
---|`dmm.ATTR_DIGI_ATRIG_MODE`
---|`dmm.ATTR_MEAS_SIM_REF_TEMP`
---|`dmm.ATTR_MEAS_APERTURE`
---|`dmm.ATTR_MEAS_RTD_BETA`
---|`dmm.ATTR_MEAS_BIAS_LEVEL`
---|`dmm.ATTR_MEAS_COUNT`
---|`dmm.ATTR_DIGI_ATRIG_EDGE_LEVEL`
---|`dmm.ATTR_MEAS_THRESHOLD_RANGE`
---|`dmm.ATTR_MEAS_FUNCTION`
---|`dmm.ATTR_DIGI_ATRIG_WINDOW_LEVEL_LOW`
---|`dmm.ATTR_MEAS_FILTER_WINDOW`
---|`dmm.ATTR_DIGI_MATH_PERCENT`
---|`dmm.ATTR_MEAS_LIMIT_LOW_2`
---|`dmm.ATTR_DIGI_LIMIT_HIGH_2`
---|`dmm.ATTR_DIGI_ATRIG_WINDOW_DIRECTION`
---|`dmm.ATTR_MEAS_INPUT_IMPEDANCE`
---|`dmm.ATTR_DIGI_LIMIT_AUDIBLE_1`
---|`dmm.ATTR_DIGI_LIMIT_ENABLE_2`
---|`dmm.ATTR_MEAS_MATH_FORMAT`
---|`dmm.ATTR_DIGI_DB_REFERENCE`
---|`dmm.ATTR_MEAS_LIMIT_ENABLE_1`
---|`dmm.ATTR_MEAS_RANGE_AUTO`
---|`dmm.ATTR_MEAS_LIMIT_AUDIBLE_1`
---|`dmm.ATTR_MEAS_REL_ENABLE`
---|`dmm.ATTR_MEAS_LIMIT_LOW_1`
---|`dmm.ATTR_MEAS_REL_LEVEL`
---|`dmm.ATTR_DIGI_REL_LEVEL`
---|`dmm.ATTR_MEAS_UNIT`
---|`dmm.ATTR_DIGI_FUNCTION`
---|`dmm.ATTR_MEAS_OFFCOMP_ENABLE`
---|`dmm.ATTR_DIGI_LIMIT_LOW_1`
---|`dmm.ATTR_MEAS_RTD_DELTA`
---|`dmm.ATTR_DIGI_LIMIT_AUTO_CLEAR_2`


