---@meta

---@alias loadFunConstParam
---| `"ConfigList"`
---| `"DurationLoop"`
---| `"Empty"`
---| `"GradeBinning"`
---| `"LogicTrigger"`
---| `"LoopUntilEvent"`
---| `"SimpleLoop"`
---| `"SortBinning"`
