name: Generate JSON and Save as Artifacts

on:
  pull_request:
     types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    tags:
      - "*"

jobs:
  build:
    name: generate-json-and-save-as-artifacts
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com

      - name: Install package from npm registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          npm install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: install requirements.txt
        run: pip install -r requirements.txt

      - name: Copy HTML file
        run: cp -r node_modules/@tektronix/web-help-documents web-help-documents

      - name: Run Python script to generate JSON
        run: python main.py web-help-documents

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-json
          path: data/
