name: Generate JSON and Save as Artifacts

on: push

jobs:
  generate-json-and-save-as-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install package from npm registry
      run: npm install web-help-documents@latest

    - name: Copy HTML file
      run: cp node_modules/your-package-name/input.html input.html

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script to generate JSON
      run: python main.py

    - name: Create artifacts directory
      run: mkdir artifacts

    - name: Copy generated JSON file to artifacts directory
      run: cp generated.json artifacts/

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: generated-json
        path: artifacts/
